* bug-mode

A mode to interface with bug/issue tracking systems from within Emacs. This mode started out as bz-mode, but got renamed to bug-mode after work was done to support additional bug trackers.

Currently somewhat working bug trackers are:

- [[https://www.bugzilla.org/][Bugzilla]]
- [[https://www.rallydev.com/][Rally]]

** Quick start

This is a quick start guide. Have a look at the [[./doc/manual.org][full manual]]
for more details.

- call =make= to generate autoloads
- Edit your ~/.emacs or ~/.emacs.d/init.el:
#+BEGIN_SRC emacs-lisp
(load-file "/path/to/bug-mode/bug.el")
#+END_SRC
- =M-x customize-group RET bug= and adjust at least the the list of instances and the name of the default instance. The instance plist configuration could look like this:
#+BEGIN_SRC emacs-lisp
(:foo (:url "https://foo.example" :type bz-rpc)
 :bar (:url "https://bar.example" :authinfo "~/.netrc" :type bz-rpc)
 :rally (:api-key "_yourapikey" :type rally))
#+END_SRC
- =M-x customize-group RET bug-faces= if you don't like the default faces
- Store your credentials in authinfo format in =~/.authinfo=, or specify a database location with the =:authinfo= property
- For using Rally, generate [[https://rally1.rallydev.com/login/accounts/index.html#/keys][API Keys]] if your subscription allows it, and set the =:api-key property=. With no API key configured username/password from authinfo are used as well.
